# Generated by Django 5.1.1 on 2024-09-15 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ice", "0002_player_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="name",
        ),
    ]
